### PR TITLE
Assign stream index on outgoing RTP packets

### PR DESCRIPTION
**Pull request by mtlynch**
This change populates the mindex field of the janus janus_plugin_rtcp struct (see https://janus.conf.meetecho.com/docs/structjanus__plugin__rtcp.html#a5a3ef3ddd4a18e0245b89a703849e2f7). The change sets mindex to 0 for a video stream and 1 for an audio stream.

Without this fix, we observed the browser fail to decode video+audio streams because it would detect sequence number reuse since the video and audio streams had the same stream index.

This change also adjusts the ordering of SDPs in janus/src/plugin.c so that the video stream always appears first. We base this decision on the assumption that uStreamer supports video-only streams and video+audio streams, but never audio-only streams. With this assumption, placing the video SDP first means the video stream will always have index 0, and the audio stream will always have index 1.

### CODE REVIEW

**Comment by mdevaev** [comment]
It's interesting. Why haven't I encountered this problem? Are there any specific conditions required?

**Comment by mtlynch** [comment]
We're puzzled as well why it's never come up before. We can't get it to work at all without this patch.

We're testing on a 32-bit Raspbian Lite system (Bullseye) on a Pi 4B, and the failure happens with every target device we've tested without this patch.

**Comment by 602p** [comment]
To clarify, we were observing the sequence number reuse issue occurring _inside_ libsrtp on the Janus/uStreamer end before packets were getting sent. So it's possible you weren't observing it due to a newer/older/differently configured version of libsrtp. 

Conjecture: I think the version we're using of libsrtp has a reuse check that is keyed to a replay database by the mindex field. This collides since mindex is always zero (set [here](https://github.com/pikvm/ustreamer/blob/640c40ad5f1c6f6c290cb926c87a177a74b820c4/janus/src/client.c#L101).) The client however is keying streams to replay databases by ssrc and since these don't collide it doesn't reject. So if you're using a version of libsrtp that doesn't do send-time replay checking, or does it by ssrc instead of mindex, it would work. I think the on-the-wire traffic is unchanged by this patch (except for reordering SDPs) since mindex doesn't go over the wire to my understanding, just the ssrc.

**Comment by mdevaev** [comment]
Which Janus version do you use? I suppose 1.x, right? Then this explains a lot because on 0.x my current code works fine, and on 0.x `mindex` does not exist at all. So the new code should be wrapped to `#if JANUS_PLUGIN_API_VERSION >= 100`.

**Comment by mtlynch** [comment]
>Which Janus version do you use? I suppose 1.x, right? Then this explains a lot because on 0.x my current code works fine, and on 0.x mindex does not exist at all. So the new code should be wrapped to #if JANUS_PLUGIN_API_VERSION >= 100.

Ah, gotcha. I'm using 1.0.1, so that explains the difference. I've added the `if` guard.

**Comment by mdevaev** [comment]
This is not enough. You need to add if-else for video/audio ordering in SDP. Keeo the old order (audio-video) for 0.x version and use the new one for the 1.x.

**Comment by mtlynch** [comment]
Sure, fixed.

**Comment by mdevaev** [comment]
Merci

**Pull request merged**
