### PR TITLE
Add upstreamer-dump manpage

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by reedy** [comment]
Not quite finished, need to add an example

**Comment by reedy** [comment]
I think this is about ready now...?

```
USTREAMER-DUMP(1)                                                            General Commands Manual                                                           USTREAMER-DUMP(1)

NAME
       ustreamer-dump - Dump uStreamer's memory sink to file

SYNOPSIS
       ustreamer-dump [OPTION]

DESCRIPTION
       µStreamer-dump (ustreamer-dump) writes a local stream from ustreamer to a file or redirect it to other utilities (such as ffmpeg).

USAGE
       ustreamer requires at least the --sink option to operate.

       To output ustreamers sink "test" to ffmpeg, and into a file called test.mp4: ustreamer-dump \
              --sink=test \ # Use ustreamer sink "test"
              --output - \ # Output to stdout
               | ffmpeg -use_wallclock_as_timestamps 1 -i pipe: -c:v libx264 test.mp4

OPTIONS
   Sink options
       -s, --sink name Memory sink ID. No default.

       -t, --sink-timeout sec
              Timeout for the upcoming frame. Default: 1.

       -o, --output filename
              Filename to dump output to. Use '-' for stdout. Default: just consume the sink.

       -j, --output-json
              Format output as JSON. Required option --output. Default: disabled.

   Logging options
       --log-level N  Verbosity  level  of  messages  from 0 (info) to 3 (debug). Enabling debugging messages can slow down the program.  Available levels: 0 (info), 1 (perfor‐
       mance), 2 (verbose), 3 (debug).  Default: 0.

       --perf Enable performance messages (same as --log-level=1). Default: disabled.

       --verbose
              Enable verbose messages and lower (same as --log-level=2). Default: disabled.

       --debug
              Enable debug messages and lower (same as --log-level=3). Default: disabled.

       --force-log-colors
              Force color logging. Default: colored if stderr is a TTY.

       --no-log-colors
              Disable color logging. Default: ditto.

   Help options
       -h, --help Print this text and exit.

       -v, --version
              Print version and exit.

BUGS
       Please file any bugs and issues at https://github.com/pikvm/ustreamer/issues

AUTHOR
       Maxim Devaev <mdevaev@gmail.com>

HOMEPAGE
       https://pikvm.org/

COPYRIGHT
       GNU General Public License v3.0

January 2021                                                                       version 2.2                                                                 USTREAMER-DUMP(1)
```

**Comment by reedy** [comment]
> I think this is about ready now...?

Ah. Just the "installation" to do. Incoming

**Comment by reedy** [comment]
> > I think this is about ready now...?
> 
> Ah. Just the "installation" to do. Incoming

Except, ustreamer-dump doesn't look to be being "installed" just yet in the packages? Just the makefile for now then

**Comment by mdevaev** [comment]
> Except, ustreamer-dump doesn't look to be being "installed" just yet in the packages? Just the makefile for now then

Current packages use a Makefile to install, so everything should be fine.

I believe that the utility is ready for use.

**Comment by reedy** [comment]
> > Except, ustreamer-dump doesn't look to be being "installed" just yet in the packages? Just the makefile for now then
> 
> Current packages use a Makefile to install, so everything should be fine.
> 
> I believe that the utility is ready for use.

I was referring to https://github.com/pikvm/ustreamer/blob/0fbb417/pkg/gentoo/ustreamer-9999.ebuild#L26-L29 which installs the `ustreamer` binary and `ustreamer.1` manpage, but not `ustreamer-dump` yet :)

**Comment by mdevaev** [comment]
Many thanks! I will fix it also.

**Pull request merged**
