### PR TITLE
Better CORS support

### PR DESCRIPTION
**Pull request by FallingSnow**
Current CORS support only adds an Access-Control-Allow-Origin header to some requests. It also does not support the OPTIONS preflight sent by modern browsers. This commit adds support for OPTIONS preflight as well as more CORS headers.

The OPTIONS preflight is sent without any credentials attached to it so it mist take place before Authorization header processing. Firefox 99 requires other access control headers like Access-Control-Allow-Headers be returned for a successful CORS interaction.

### CODE REVIEW

**Comment by FallingSnow** [comment]
In the future, if I end up getting around to it, I'd like to add the functionality to use a `*` to dynamically set allow-origin to the request's host/origin header.

**Comment by mdevaev** [comment]
Sup. Should the `allow_origin` logic also be changed in `_http_callback_stream_write()`?

**Comment by FallingSnow** [comment]
Yo. Yes, probably. How come `_http_callback_stream_write()` doesn't already call `PREPROCESS_REQUEST;`? I assume this has to do something with the fact that it's a stream.

**Comment by FallingSnow** [comment]
Never mind, I see it now. Yeah, that'll need to be changed.

**Comment by mdevaev** [comment]
Will you fix it?

**Comment by FallingSnow** [comment]
Yeah. I'll try to get around to it today or tomorrow.

**Comment by mdevaev** [comment]
Thanks!

**Pull request merged**
